repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.3.3
    hooks:
      - id: gdformat
        args: [--check]
        files: \.gd$
      - id: gdlint
        files: \.gd$

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
